spring:

  h2:
    console:
      enabled: true
#      settings:
#        web-allow-others: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/pseuteam
    username: sa
    password:
    driver-class-name: org.h2.Driver

  file:
    upload:
      location: media

  jpa:
    hibernate:
      ddl-auto: create  # create: 자동으로 테이블 생성(애플리케이션 생성 시점에 기존 테이블을 전부 삭제하고 다시 생성), none: 기존 테이블을 삭제하지 않음
    properties:
      hibernate:
        #        show_sql: true  # sout을 통해 실행 sql 로그 출력
        format_sql: true


logging:
  level:
    org.hibernate.sql: debug  # logger를 통해 실행 sql 로그 출력
    org.hibernate.type: trace


jwt:
  secret:
    asjkdfjkha32434294@!*dkasjd1213123-0@d10@#*$&*&%d12od12d00di1id93d3dj13hd1309ud13